import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsInt,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';

/** `{ id }` of a region; other fields the app sends are stripped. */
export class RegionRefInput {
  @IsInt()
  @Min(1)
  @ApiProperty()
  id: number;
}

export class CreateFastingInput {
  @IsInt()
  @Min(1)
  @ApiProperty()
  id: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty()
  firstName: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty()
  lastName: string;

  @IsString()
  @IsOptional()
  @ApiProperty({ required: false })
  cin: string;

  @IsNumber()
  @IsNotEmpty()
  @ApiProperty()
  region: number;

  @IsString()
  @IsOptional()
  @ApiProperty()
  comment: string;

  @IsString()
  @IsOptional()
  @ApiProperty()
  phone: string;

  @IsInt()
  @Min(0)
  @Max(50)
  @ApiProperty()
  singleMeal: number;

  @IsInt()
  @Min(0)
  @Max(50)
  @ApiProperty()
  familyMeal: number;

  @IsDateString()
  @IsOptional()
  @ApiProperty()
  lastTakenMeal: Date;

  @IsOptional()
  @IsArray()
  takenMeals: Date[];

  @IsBoolean()
  @IsOptional()
  @ApiProperty()
  cameToday: boolean;
}

export class UpdateFastingInput {
  @IsString()
  @IsNotEmpty()
  @ApiProperty()
  firstName: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty()
  lastName: string;

  @IsString()
  @IsOptional()
  @ApiProperty({ required: false })
  cin: string;

  /** Only a global admin may move a person; others must send the URL region. */
  @IsOptional()
  @ValidateNested()
  @Type(() => RegionRefInput)
  @ApiProperty({ required: false, type: () => RegionRefInput })
  region?: RegionRefInput;

  @IsString()
  @IsOptional()
  @ApiProperty()
  comment: string;

  @IsString()
  @IsOptional()
  @ApiProperty()
  phone: string;

  @IsInt()
  @Min(0)
  @Max(50)
  @ApiProperty()
  singleMeal: number;

  @IsInt()
  @Min(0)
  @Max(50)
  @ApiProperty()
  familyMeal: number;

  @IsDateString()
  @IsOptional()
  @ApiProperty()
  lastTakenMeal: Date;

  @IsOptional()
  @IsArray()
  takenMeals: Date[];
}

/**
 * Body of `PATCH /fastings/confirm/:region/:id`.
 * Only phone and comment may change while confirming a meal; the meal
 * history is maintained exclusively by the server. Any other property sent
 * by older clients (e.g. the full person object) is stripped by the
 * whitelist validation pipe.
 */
export class ConfirmMealInput {
  @IsString()
  @IsOptional()
  @ApiProperty({ required: false })
  phone?: string;

  @IsString()
  @IsOptional()
  @ApiProperty({ required: false })
  comment?: string;

  /**
   * Generated by the app per confirm and reused on every retry of it, so a
   * retry can never record a second meal (spec 2A §4.1).
   */
  @IsUUID('4')
  @IsOptional()
  @ApiProperty({ required: false, format: 'uuid' })
  clientEventId?: string;

  /** Installation ID of the phone, for the audit trail. */
  @IsString()
  @MaxLength(64)
  @IsOptional()
  @ApiProperty({ required: false, maxLength: 64 })
  deviceId?: string;
}
