/** Machine-readable error codes returned in `error.details.code`. */
export const FASTING_ERROR_CODES = {
  MEAL_ALREADY_TAKEN: 'MEAL_ALREADY_TAKEN',
  PERSON_ID_TAKEN: 'PERSON_ID_TAKEN',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  CLIENT_EVENT_ID_REUSED: 'CLIENT_EVENT_ID_REUSED',
  MEAL_EVENT_NOT_FOUND: 'MEAL_EVENT_NOT_FOUND',
  UNDO_NOT_ALLOWED: 'UNDO_NOT_ALLOWED',
  UNDO_WINDOW_EXPIRED: 'UNDO_WINDOW_EXPIRED',
} as const;
