version: '3.8'

services:
  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:8080"  # Traefik dashboard
    
  app:
    build:
      args:
        - APP_ENV=development
    command: pnpm start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules/

  pgsqldb:
    ports:
      - "5432:5432"

  adminer:
    ports:
      - "8080:8080"
